name       : libgnome-keyring
version    : 3.12.0
release    : 10
source     :
    - http://ftp.gnome.org/pub/GNOME/sources/libgnome-keyring/3.12/libgnome-keyring-3.12.0.tar.xz : c4c178fbb05f72acc484d22ddb0568f7532c409b0a13e06513ff54b91e947783
homepage   : https://live.gnome.org/GnomeKeyring
license    : GPL-3.0
component  : desktop.gnome.core
summary    : The libgnome-keyring is used by applications to integrate with the GNOME
    Keyring system.
description: |
    The libgnome-keyring is used by applications to integrate with the GNOME Keyring system.
builddeps  :
    - libgcrypt-devel
    - vala
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
